cart/urls.py
from django.urls import path
from . import views 



app_name = "cart"


urlpatterns = [
	path("",views.cart_detail,name="cart_detail"),
	path("add/<int:product_id>/",views.cart_add,name="cart_add"),
	path("remove/<int:product_id>/",views.cart_remove,name="cart_remove"),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("cart/",include("cart.urls",namespace="cart")),
    path("orders/",include("orders.urls",namespace="orders")),
    path("payment/",include("payment.urls",namespace="payment")),
    path("coupon/",include("coupons.urls",namespace="coupons")),
    path("",include("shop.urls",namespace="shop")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
    

shop/urls.py
from django.urls import path
from . import views 


app_name="shop"


urlpatterns=[
	path("",views.product_list,name="product_list"),
	path("home/",views.home,name="home"),
	path("<slug:category_slug>/",views.product_list,name="product_list_by_category"),
	path("<int:id>/<slug:slug>/",views.product_detail,name="product_detail"),
]

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
	name = models.CharField(max_length=200)
	slug= models.SlugField(max_length=200,unique=True)

	class Meta:
		ordering=['name']
		indexes = [
		models.Index(fields=['name']),
		]
		verbose_name = "category"
		verbose_name_plural = "categories"

	def __str__(self):
		return self.name  

	def get_absolute_url(self):
		return reverse("shop:product_list_by_category",args=[self.slug])




class Product(models.Model):
	category = models.ForeignKey(Category,related_name = 'products', on_delete=models.CASCADE)
	name = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200)
	image = models.ImageField(upload_to="products/%Y/%m/%d",blank=True)
	description = models.TextField(blank=True)
	price = models.DecimalField(max_digits=10,decimal_places=2)
	available=models.BooleanField(default=True)
	created=models.DateTimeField(auto_now_add=True)
	updated=models.DateTimeField(auto_now=True)


	class Meta:
		ordering=['name']
		indexes = [
		models.Index(fields=['id','slug']),
		models.Index(fields=['name']),
		models.Index(fields=['-created']),
		]

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("shop:product_detail",args=[self.id,self.slug])

shop/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product
from cart.forms import CartAddProductForm
from cart.cart import Cart
from .recommender import Recommender

def product_list(request,category_slug=None):
	category=None
	categories = Category.objects.all()
	products = Product.objects.filter(available=True)

	if category_slug:
		category = get_object_or_404(Category,slug=category_slug)
		products = products.filter(category=category)
	return render(request,"shop/product/list.html",{"category":category,"categories":categories,"products":products})
	
def product_detail(request,id,slug):
	product=get_object_or_404(Product,id=id,slug=slug,available=True)
	cart_product_form = CartAddProductForm()
	r=Recommender()
	recommended_products = r.suggest_products_for([product],4)
	return render(request,"shop/product/detail.html",{"product":product,"cart_product_form":cart_product_form,"recommended_products":recommended_products})

def home(request):
	products = Product.objects.filter(available=True)
	return render(request,"shop/home.html",{"products":products})

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static 'shop/base.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="header">
            <a href="/" class="logo">My shop</a>
        </div>
        <div id="subheader">
            <div class="cart">
            {%with total_items=cart|length%}
                {%if total_items > 0%}
                    Your Cart:
                    <a href="{%url 'cart:cart_detail'%}">
                        {{total_items}} item{{total_items|pluralize}},
                        ${{cart.get_total_price}}
                    </a>
                {%elif not order%}
                    Your cart is empty
                {%endif%}
            {%endwith%}
            </div>
        </div>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

shop/templates/shop/home.html
{%extends "shop/shopbase.html"%}
{% block content %}            
	<section id="hero">
		<h4>Trade in offer</h4>
		<h2>Super Value deals</h2>
		<h1>On all our products</h1>
		<p>Save more with coupons & up to 70% off!</p>
		<button>Shop Now</button>
	</section>

	{%include "shop/features_and_banners/features.html"%}

	<section id="product1" class="section-p1">
		<h2>Featured Prodcut</h2>
		<p>Summer Collection New Modern Design</p>
		<div class="pro-container">
			<div class="pro">
				<img src="img/products/f1.jpg" alt="">
				<div class="des">
					<span>adidas</span>
					<h5>Cartoon astronaut T-shirt</h5>
					<div class="star">
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
					</div>
					<h4>$77</h4>
				</div>
				<a href="#"><i class="fa-solid fa-cart-shopping cart"></i></a>
			</div>

			<div class="pro">
				<img src="img/products/f2.jpg" alt="">
				<div class="des">
					<span>adidas</span>
					<h5>Cartoon astronaut T-shirt</h5>
					<div class="star">
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
					</div>
					<h4>$77</h4>
				</div>
				<a href="#">
					<i class="fa-solid fa-cart-shopping cart"></i>
				</a>
			</div>

			<div class="pro">
				<img src="img/products/f3.jpg" alt="">
				<div class="des">
					<span>adidas</span>
					<h5>Cartoon astronaut T-shirt</h5>
					<div class="star">
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
					</div>
					<h4>$77</h4>
				</div>
				<a href="#">
					<i class="fa-solid fa-cart-shopping cart"></i>
				</a>
			</div>

			<div class="pro">
				<img src="img/products/f4.jpg" alt="">
				<div class="des">
					<span>adidas</span>
					<h5>Cartoon astronaut T-shirt</h5>
					<div class="star">
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
					</div>
					<h4>$77</h4>
				</div>
				<a href="#">
					<i class="fa-solid fa-cart-shopping cart"></i>
				</a>
			</div>

			<div class="pro">
				<img src="img/products/f5.jpg" alt="">
				<div class="des">
					<span>adidas</span>
					<h5>Cartoon astronaut T-shirt</h5>
					<div class="star">
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
					</div>
					<h4>$77</h4>
				</div>
				<a href="#">
					<i class="fa-solid fa-cart-shopping cart"></i>
				</a>
			</div>

			<div class="pro">
				<img src="img/products/f6.jpg" alt="">
				<div class="des">
					<span>adidas</span>
					<h5>Cartoon astronaut T-shirt</h5>
					<div class="star">
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
					</div>
					<h4>$77</h4>
				</div>
				<a href="#">
					<i class="fa-solid fa-cart-shopping cart"></i>
				</a>
			</div>

			<div class="pro">
				<img src="img/products/f7.jpg" alt="">
				<div class="des">
					<span>adidas</span>
					<h5>Cartoon astronaut T-shirt</h5>
					<div class="star">
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
					</div>
					<h4>$77</h4>
				</div>
				<a href="#">
					<i class="fa-solid fa-cart-shopping cart"></i>
				</a>
			</div>

			<div class="pro">
				<img src="img/products/f8.jpg" alt="">
				<div class="des">
					<span>adidas</span>
					<h5>Cartoon astronaut T-shirt</h5>
					<div class="star">
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
					</div>
					<h4>$77</h4>
				</div>
				<a href="#">
					<i class="fa-solid fa-cart-shopping cart"></i>
				</a>
			</div>
		</div>
	</section>

	<section id="banner" class="section-m1">
		<h4>Repair Services</h4>
		<h2>Up to <span>70% off</span> - All t-Shirts & Accessories</h2>
		<button class="normal">Explore More</button>
	</section>

	<section id="product1" class="section-p1">
		<h2> New Arrivals</h2>
		<p>Summer Collection New Modern Design</p>
		
			<div class="pro-container">
				{% for product in products %}
					<div class="pro">
						<img src="{%if product.image%}{{product.image.url}}{%endif%}" alt="">
						<div class="des">
							<span>{{product.name}}</span>
							<h5>{{product.name}}</h5>
							<div class="star">
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
							</div>
							<h4>${{product.price}}</h4>
						</div>
						<a href="#"><i class="fa-solid fa-cart-shopping cart"></i></a>
					</div>
				{%endfor%}
			</div>
		
	</section>

	<section id="sm-banner" class="section-p1">
		<div class="banner-box">
			<h4>Crazy deals</h4>
			<h2>But 1 get 1 free</h2>
			<span>The best classic dress is on sale</span>
			<button class="white">Learn More</button>
		</div>
		<div class="banner-box banner-box-2">
			<h4>Spring/Summer</h4>
			<h2>upcomming season</h2>
			<span>The best classic dress is on sale</span>
			<button class="white">Collection</button>
		</div>
	</section>

	<section id="banner3">
		<div class="banner-box">
			<h2>Seasonal SALE</h2>
			<h3>Winter Collection -50% OFF</h3>
		</div>
		<div class="banner-box banner-box-2">
			<h2>NEW FOOTWEAR COLLECTION</h2>
			<h3>Spring / Summer 2023</h3>
		</div>
		<div class="banner-box banner-box-3">
			<h2>T-SHIRTS</h2>
			<h3>New Trendy prints</h3>
		</div>
	</section>

{% endblock %}

<script type="text/javascript" src="website.js"></script>
</body>
</html>

shop/templates/shop/shopbase.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static 'shop/main.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a34dbf6751.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <section id="header">
            <a href="#"> <img src="img/logo.png" class="logo"></a>
            <div>
                <ul id="navbar">
                    <li><a class="active" href="index.html">Home</a></li>
                    <li><a href="shop.html">Shop</a></li>
                    <li><a href="blog.html">Blog</a></li>
                    <li><a href="about.html">About</a></li>
                    <li><a href="contact.html">Contact</a></li>
                    <li><a id="lg-bag" href="cart.html"><i class="fa-solid fa-cart-plus"></i></a></li>
                    <a href="" id="close"><i class="fa-solid fa-xmark"></i></a>
                </ul>
            </div>
            <div id="mobile">
                <a href="cart.html"><i class="fa-solid fa-cart-plus"></i></a>
                <i id="bar" class="fas fa-outdent"></i>
            </div>
        </section>

        <!-- BLOCK CONTENT -->

        <div id="content">
            {% block content %}
            {% endblock %}
        </div>

        <!-- NEWSLETTER SECTION  -->

        <section id="newsletter" class="section-p1 section-m1">
            <div class="newstext">
                <h4>
                    Sign up for newsletter
                </h4>
                <p>Get E-mail updates about or latest shop and <span>special offers.</span></p>
            </div>
            <div class="form">
                <input type="text" name="email" placeholder="Your email address">
                <button class="normal">
                    Sign Up
                </button>
            </div>
        </section>


        <!-- FOOTER SECTION -->

        <footer class="section-p1">
            <div class="col">
                <img class="logo" src="img/logo.png" alt="">
                <h4>Contact</h4>
                <p><strong>Address:</strong> 562 Wellington Road, Street 32, San Francisco</p>
                <p><strong>Phone:</strong> +91 7872944208</p>
                <p><strong>Hours:</strong> 10:00 - 18:00 Mon-Sat</p>
                <div class="follow">
                    <h4>Follow Us</h4>
                    <div class="icon">
                        <i class="fab fa-facebook-f"></i>
                        <i class="fab fa-twitter"></i>
                        <i class="fab fa-instagram"></i>
                        <i class="fab fa-pinterest-p"></i>
                        <i class="fab fa-youtube"></i>
                    </div>
                </div>
            </div>
            <div class="col">
                <h4>About</h4>
                <a href="">About Us</a>
                <a href="">Delivery Information</a>
                <a href="">Privacy Policy</a>
                <a href="">Terms & Conditions</a>
                <a href="">Contact Us</a>
            </div>
            <div class="col">
                <h4>My Account</h4>
                <a href="">Sign In</a>
                <a href="">View Cart</a>
                <a href="">My Wishlist</a>
                <a href="">Track My Orders</a>
                <a href="">Help</a>
            </div>
            <div class="col install">
                <h4>Install App</h4>
                <p>From App store or Google Play</p>
                <div class="row">
                    <img src="img/pay/app.jpg">
                    <img src="img/pay/play.jpg">
                </div>
                <p>Secured Payment Gateways</p>
                <img src="img/pay/pay.png">
            </div>


            <div class="copyright">
                <p>&copy; 2023, Vijay - Html css js</p>
            </div>
        </footer>
    </body>
</html>